---
title: "2026-02-10 - 2026 Winter Olympics"
author: "Cole Baril"
format: html
editor: source
---

```{r, load_packages}
require(pacman)
p_load(tidytuesdayR, tidyverse, janitor, here, trashpanda, ggside)
```

```{r, tt_data}
tuesdata <- tidytuesdayR::tt_load('2026-02-10')
schedule <- tuesdata$schedule
```

```{r, cleaning}
schedule_intervals <- schedule |> 
  mutate(length = end_datetime_local - start_datetime_local)

min(schedule_intervals$length)
max(schedule_intervals$length)

# Events range from 2 minutes to 254 minutes 
  
events <- schedule |> 
  select(-date, -day_of_week) |> 
  distinct(.keep_all = TRUE)

time_grid <- tibble(
  time = seq(
    from = floor_date(min(events$start_datetime_local), "hour"),
    to   = ceiling_date(max(events$end_datetime_local), "hour"),
    by   = "60 min"
  )
)

density <- events |>
  mutate(key = 1) |>
  inner_join(time_grid |> mutate(key = 1), by = "key", relationship = "many-to-many") |>
  filter(start_datetime_local <= time, end_datetime_local > time) |>
  count(time, discipline_name, name = "n_events") |> 
  mutate(total = sum(n_events), .by = discipline_name) |> 
  mutate(discipline_name = fct_reorder(discipline_name, total))

sidex <- density |> 
  summarise(total_events = sum(n_events), .by = time)

sidey <- events |> 
  summarise(total_events = n(), .by = discipline_name)



ggplot(density, aes(x = time, y = discipline_name)) +
  geom_point(aes(size = n_events, fill = discipline_name), alpha = 0.85, 
             position = position_jitter(),
             pch = 21, colour = "black") +
    geom_xsideline(
    data = sidex,
    aes(y = total_events, x = time),
    inherit.aes = FALSE,
    linewidth = 1,
    colour = "cadetblue4",
    alpha = 0.9) +
  geom_ysidecol(
    data = sidey,
    aes(x = total_events, y = discipline_name),
    inherit.aes = FALSE,
    fill = "cadetblue4",
    alpha = 0.9
    ) +
  scale_size_continuous(range = c(2, 5), guide = guide_legend(nrow = 1)) +
  scale_xsidey_continuous(breaks = c(2, 5, 8)) +
  scale_fill_viridis_d(option = "mako", guide = "none") +
  scale_x_datetime(
  expand = c(0.005, 0),
  date_breaks = "2 days",
  date_labels = "%b %d") +
  labs(
    title = "There are usually more curling events happening concurrently at any given time than any other Olympic sport",
    subtitle = "Event counts represented by dot size and binned by hour.Top ridge line represents the number of\nevents happening in each hour. Side ridge bar plot represents the total number of events for each sport discipline.",
    x = NULL,
    y = "Sport Discipline",
    size = "Concurrent Events") +
   theme_cole(remove_grid = TRUE) +
   theme(legend.position = "top") +
   add_caption_cwb(type = "plot") 

ggsave(plot = last_plot(), dpi = 300, width = 10, height = 7, filename = here("concurrent_olympic_events.png"))
   





```





## References
```{r, ref, echo = TRUE, results = 'asis', comment = NA}
cwb::cite_packages(format = "rmd")
```