---
title: "TidyTuesday 2025-09-09 - Passport Power"
author: "Cole Baril"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: false
---

<style>
mark {
  background-color: #FFF8DC; /* Green background */
  color: black; /* White text color for contrast */
  padding: 0.2em; /* Optional: add some padding for better visual appearance */
  border-radius: 3px; /* Optional: add rounded corners */
}
</style>


<style>
body, p, h1, h2, h3, h4, h5, h6 {
  background-color: white;
  color: black; 
  font-family: Courier New;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 12, fig.asp = .7, out.width = "90%", echo = FALSE, warning = FALSE, message = FALSE)

require(pacman)
p_load(spellbook, tidytuesdayR, tidyverse, janitor, tidytext, extrafont, here, 
       sf, rnaturalearth, rnaturalearthdata, patchwork, ggflags, gt, gtExtras)
```

```{r, load_clean}
tuesdata <- tidytuesdayR::tt_load('2025-09-09')

country_lists <- tuesdata$country_lists
rank_by_year <- tuesdata$rank_by_year

world <- rnaturalearth::ne_countries(scale = 50) |> 
  filter(admin != "Antarctica") |> 
  select(admin, iso_a2) |> 
  left_join(rank_by_year, by = c("iso_a2" = "code"))
```

### <mark> __2025 Passport Power Map__ </mark>

```{r, world_map}
world |> 
  filter(year == "2025") |> 
  ggplot() +
  geom_sf(aes(fill = visa_free_count), colour = "white", linewidth = 0.2) +
  scale_fill_viridis_c("Visa-Free Entry Count", end = 0.9) +
  theme_void() +
  theme_parchment() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()
        ) +
  labs(title = "2025 Passport Power",
       subtitle = "Number of countries that can be visited via its passport")
```

### <mark> __Top and Bottom 10 Countries__ </mark>

```{r, table_high}
t <- world |> 
  st_drop_geometry() |> 
  filter(!year %in% c("2007", "2009")) |>
  select(iso_a2, country, visa_free_count, year) |> 
  arrange(year, .by = country) |> 
  reframe(visa_free_count_list = list(visa_free_count),
          .by = country) |> 
  drop_na(country)
  
world |> 
  st_drop_geometry() |> 
  filter(year %in% c("2025", "2024")) |>
  select(iso_a2, country, visa_free_count, year) |> 
  pivot_wider(names_from = year, values_from = visa_free_count) |> 
  relocate(`2025`, .before = `2024`) |> 
  mutate(change = `2025` - `2024`) |> 
  left_join(t, by = "country") |> 
  arrange(desc(`2025`)) |> 
  head(10) |> 
  gt() |> 
  fmt_flag(columns = iso_a2) |> 
  cols_add(dir = ifelse(`2024` < `2025`, "arrow-up", "arrow-down")) |> 
  fmt_icon(
    columns = dir,
    fill_color = c("arrow-up" = "green", "arrow-down" = "red")
  ) |> 
  cols_hide(c(`2025`, `2024`)) |>
  cols_move(dir, after = change) |> 
  gt_plt_sparkline(column = visa_free_count_list,
                   fig_dim = c(20, 30)) |> 
  cols_label(iso_a2 = "",
             dir = "",
             country = "Country",
             change = "2024-2025 Change",
             visa_free_count_list = "Visa Free Count \nOver Time (2006-2025)") |> 
  cols_align(columns = 5, align = "center") |> 
  tab_header(
    title = md("**Top 10 Most Powerful Passports**")
  ) |> 
  opt_table_font(font = "Courier New") |> 
    tab_options(
    table.background.color = "cornsilk"
  )
```

```{r, table_low}
t <- world |> 
  st_drop_geometry() |> 
  filter(!year %in% c("2007", "2009")) |>
  select(iso_a2, country, visa_free_count, year) |> 
  arrange(year, .by = country) |> 
  reframe(visa_free_count_list = list(visa_free_count),
          .by = country) |> 
  drop_na(country)
  
world |> 
  st_drop_geometry() |> 
  filter(year %in% c("2025", "2024")) |>
  select(iso_a2, country, visa_free_count, year) |> 
  pivot_wider(names_from = year, values_from = visa_free_count) |> 
  relocate(`2025`, .before = `2024`) |> 
  mutate(change = `2025` - `2024`) |> 
  left_join(t, by = "country") |> 
  arrange(`2025`) |> 
  head(10) |> 
  gt() |> 
  fmt_flag(columns = iso_a2) |> 
  cols_add(dir = ifelse(`2024` < `2025`, "arrow-up", "arrow-down")) |> 
  fmt_icon(
    columns = dir,
    fill_color = c("arrow-up" = "green", "arrow-down" = "red")
  ) |> 
  cols_hide(c(`2025`, `2024`)) |>
  cols_move(dir, after = change) |> 
  gt_plt_sparkline(column = visa_free_count_list,
                   fig_dim = c(20, 30)) |> 
  cols_label(iso_a2 = "",
             dir = "",
             country = "Country",
             change = "2024-2025 Change",
             visa_free_count_list = "Visa Free Count \nOver Time (2006-2025)") |> 
  cols_align(columns = 5, align = "center") |> 
  tab_header(
    title = md("**Top 10 Least Powerful Passports**")
  ) |> 
  opt_table_font(font = "Courier New") |> 
  tab_options(
    table.background.color = "cornsilk"
  )
```
