---
title: "2026-02-03 - Edible Plants Database"
author: "Cole Baril"
format: html
editor: source
---

```{r, load_packages}
require(pacman)
p_load(tidytuesdayR, tidyverse, janitor, here, trashpanda)
```

```{r, tt_data}
tuesdata <- tidytuesdayR::tt_load('2026-02-03')
edible_plants <- tuesdata$edible_plants
```

```{r}
edible_plants |>
  mutate(
    water = factor(str_to_title(str_trim(water)),
                   levels = c("Very High", "High", "Medium", "Low", "Very Low")),
    sunlight = factor(str_to_title(str_trim(sunlight)))
  ) |>
  ggplot(aes(x = sunlight, y = water, colour = cultivation)) +
  geom_jitter(alpha = 0.7, size = 3) +   
  scale_x_discrete(labels = function(x) str_replace_all(x, "/" , "\n")) +

  labs(
    title = "Most edible plants like a lot of sun, but a moderate amount of water",
    x = "Sunlight Requirements",
    y = "Water Requirements") +
  scale_cwb("Cultivation", type = "d", aesthetics = "colour", palette = "discrete_21") +
  theme_cole(remove_grid = TRUE) +
  theme(axis.title.x = element_text(margin = margin(t = 5))) +
  add_caption_cwb()



```



## References
```{r, ref, echo = TRUE, results = 'asis', comment = NA}
cwb::cite_packages(format = "rmd")
```